### ISSUE TITLE
Link to HTML view

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#2]
Hi,
Where do I find the HTML pages for this lab?
Br
Johnny Raadshøj

**Comment by janeteblake** [comment]
Hi Johnny, these have just posted to https://microsoftlearning.github.io/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing/
Thank you for your feedback!
Janet
