### ISSUE TITLE
Lab 1a - issue on exercise 4, step 34, clearer instructions required

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#49]
# Module: 2  -case study 1a
#### Step: 34

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188631262-ee6938b7-8e68-4a8a-a602-9abb415c6487.png)

Repro steps:

1.when closing all pages, the route could not be updated, it is complaining about primary operation not specified as per screen shot, i was able to carry on, starting exercise 5 -- there was no further impact detected.

Please advise of how to potentially fix this error to avoid receiving the error message. or please update the lab to clarify for students that it is ok to receive this error and that i can be ignored.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! The error on the priority controls simultaneous operations on a route. If there are no simultaneous operations on a route, all operations are to be created as primary. The error is valid as a warning for the secondary priority 1 option as there is no primary for "Packing". The content has been updated to primary priority operation for simultaneous route processing.

![image](https://user-images.githubusercontent.com/104943975/195957320-15e02856-481c-4f03-bd86-6161234c6058.png)
