### ISSUE TITLE
Lab 1b, exercise 3, clearer instructions required

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#50]
# Module: 2 - case study 1b
#### Step: 13

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188657826-720516e5-9b66-4d01-b1b0-56647575c0bb.png)

Repro steps:

1. The Product P17000 is set up as a co-product, not a by-product
2. I could change the production type field and set to by-product, but i don't know if that is what is intended. When you read on to step 13 - that appears to be the case.... however:
3. When you read on to step 14 it talks about setting the cost allocation percent to 32 (no mention of the by-product burden amount.

for that reason, i have left the setting on P17000 as a co-product, and i have set co-product cost allocation field to manual, with cost allocation percent at 32.

Would someone please update the lab to clarify what is required here.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 3 Step 13. We are reviewing this and will provide an update once a resolution is in place.

**Comment by chaast** [comment]
ok, thank you- i can confirm that the exercise is clear now you have made the updates to the lab descriptions.
