### ISSUE TITLE
Lab 1b - exercise 16: clearer instructions required

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#51]
# Module: 2 - case study 1b
#### Step: 04

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188695631-7a2598df-4b61-4e90-8f74-536de0b7e719.png)

Repro steps:

1. when clicking on load item attributes - there are no records loaded. it is unclear from the steps where to fill in the attribute value of "163" in step 4.

The fix: I noticed in the exercise introduction the mention of item number P4000 -- not PW4000. Step 4 of this exercise needs to be updated, because when i select Item number P4000 then the exercise runs ok.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 16 Step 4. We are reviewing this and will provide an update once a resolution is in place.

**Comment by chaast** [comment]
hi can you please let me know when you are able to update the fix. it is only a small change required on step 4 --
 the user needs to pick item number P4000, not PW4000 -- if they do this, then the exercise is ok.

thank you

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 16 Step 4. Item number PW400 corrected to P4000. Looks like the attribute may not have been created. The attribute value is supposed to be associated to the batch attribute record. When attributes are created, they will appear to associate in relation to the attribute. Creating the batch attribute for MeltingPoint and associating the batch attribute to an item such as P4000 and to the customer US-024 would clear the relation to the attribute. The task for this would have been in Case Study According to 1B Exercise 15.
