### ISSUE TITLE
Lab 1b - exercise 17 - receive purchase order, clearer instructions required

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#52]
# Module: 2 - lab 1b
#### Step: 05

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188701414-f0c5f6f6-405e-4141-a2b4-b8f1d13bf804.png)

Repro steps:

1. Please make it clear to students that the field "arrival overview profile name" must show the value of "inquiry", not "today" for the create PO to appear in the receipts grid.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 17 Step 5. We are reviewing this and will provide an update once a resolution is in place.

**Comment by chaast** [comment]
hi- could you please let me know when you are able to update the lab - it should be an easy fix... if the student pick the arrival overview profile name of "inquiry" then the labs runs ok.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 17 Step 5. We appreciate your suggestion, and this has been incorporated.

**Comment by mstall1ngs** [comment]
Update to this inquiry as a notation: The Arrival overview profile name field has been updated. This should provide the option to use Today as a value.
