### ISSUE TITLE
Lab 1b, exercise 19: issue, managed to fix it - but please update the lab instructions in this exercise

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#54]
# Module: 2 - lab 1b
#### Step: 7

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188834064-be56b8ac-1394-4ab1-b2b1-115c2648f125.png)

Repro steps:

1. whichever vendor i pick for the purchase order, none are authorised to sell the new product i created, and an error occured whilst posting.

Please advise how to fix.

**Comment by chaast** [comment]
I went back to this exercise today.. i created a new product number but had these errors as per screen shot below

![image](https://user-images.githubusercontent.com/89986870/190896073-bf159f66-a036-4a94-8a59-0c1683b3205d.png).


I then tried to change the order quantity to 20 instead of 15 (bearing in mind that in the previous exercise we were asked to put the inventory CW unit minimum quantity to 19. I also went to financial dimensions in the line details section  and I selected ProductGroup OJ B2B. this got rid of the error message.

Please update the lab instructions to include a step to add the product group.

**Comment by chaast** [comment]
**also in this exercise -- in the section create and post an arrival journal for the purchase order**

 - please clarify in step 17 how people need to follow the link in the batch number field. New users will not be familiar with this process... instructions should include: "right hand mouse click on the drop down arrow, then select view details" before moving to step 18
 - and step 25 - the quantity of 295, might not meet the minimum order quantity in which case the user may need to fill in a quantity of 380.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercises 19. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
This has been updated with release version 10.0.29.

![image](https://user-images.githubusercontent.com/104943975/233508352-6f21416d-e02c-406c-acb7-785d6c424932.png)

**Comment by mstall1ngs** [comment]
This has been updated with release version 10.0.29. Please review screenshot for confirmed PO.

![image](https://user-images.githubusercontent.com/104943975/233508352-6f21416d-e02c-406c-acb7-785d6c424932.png)
