### ISSUE TITLE
Lab 1b - exercise 20 -- clearer instructions required

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#55]
# Module: 2, lab 1b
#### Step: 7

Description of issue

when you click on confirm the user may see an error message as per screenshot below.
In the lab instructions, please inform the user to fill in the product group dimension on the financial dimension tab in line details.

![image](https://user-images.githubusercontent.com/89986870/190897271-d6ad66da-0976-4a0e-b069-c783ad9226c1.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 20 Step 7. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercises 20. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
The steps for assigning the default financial dimension to the item is located in Exercise 15. Here you are able to expand Financial dimensions FastTab, select a product group for the ProductGroup financial dimension to assign an item to. The screenshot is showing a different item number, however, the objective is the same.

**Comment by mstall1ngs** [comment]
The steps for assigning the default financial dimension to the item is located in Exercise 15. Here you are able to expand Financial dimensions FastTab, select a product group for the ProductGroup financial dimension to assign an item to. The screenshot is showing a different item number, however, the objective is the same.

![image](https://user-images.githubusercontent.com/104943975/233510557-aec87fae-a052-47a8-8485-e3f0a5eb03c3.png)
