### ISSUE TITLE
Lab 1b, exercise 23 - clearer instructions needed

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#56]
# Module 02, lab 1b
#### Step: 16

Description of issue
clearer instructions needed... when i typed AB(D/C) as instructed, the lab came back with an issue... however when i changed the formula to read A+B*(D/C) the error disappeared.

![image](https://user-images.githubusercontent.com/89986870/190898701-9cc7c7a8-d2d1-47e4-9aae-94f7034a528c.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 23 Step 16. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Error message of the issue was not provided. Unable to duplicate error. 

![image](https://user-images.githubusercontent.com/104943975/233511844-c81efdd7-a44e-4a87-8924-9d5d2b8193fe.png)
