### ISSUE TITLE
Lab 1b, exercise 24 - clearer instructions needed

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#57]
# Module: 2, lab 1b
#### Step: 08

Description of issue
In step 8, before confirming the PO, Please remind users to go to financial dimensions to select a product group

#### Step: 04

Description of issue
It is not so clear to click on line details below the grid to update line and registration details.

#### Step: 01

Description of issue
In step 1 it is not so clear where to find the quantity field (from what i could see it was already filled in), so then i closed the page - let the record post and then i could continue nicely with step 3.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercise 24 Steps 8, 1 & 4. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Step 1 in all exercises will have the navigation of where to go to complete the exercise. For Exercise #24: Record a potency attribute upon receipt (Bonus), step 1 is **Go to Procurement and sourcing > Purchase orders > All purchase orders.** After you select OK in step 5, you will see the newly created purchase order that you created in steps 2 - 4. 
![image](https://user-images.githubusercontent.com/104943975/233512876-e6ddb443-f1c2-47aa-96f9-ec60399b3c64.png)

Step 6 is where you will enter the **M2004** in the **Item number** field. 
Step 8 is where you will enter the **Quantity** to **800**

![image](https://user-images.githubusercontent.com/104943975/233514622-d97541b4-4966-4c57-a113-8aa57e13d3be.png)
