### ISSUE TITLE
Lab 1b, exercise 25 - ISSUE, UNABLE TO PROCEED AND COMPLETE 

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#58]
# Module: 02, Lab 1b
#### Step: 09

Description of issue
Upon starting production - I was unable to proceed because not enough capacity could be found.
Unable to proceed with the remainder of the exercise.

* Please advise on how to fix

![image](https://user-images.githubusercontent.com/89986870/190900102-af7506f2-7241-4175-8688-c173bc39d0fa.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! You can schedule production at the operation level and the job level. Operations scheduling controls the planning method of the scheduling direction (forward or backward) from a given date, optimize the use of resources by scheduling productions based on the capacity of the resources as well as optimize the use of materials by scheduling productions based on the availability of the required materials.  Job scheduling is more detailed than operations scheduling but you will gain more regarding capacity.

Before starting the process on the production order, you must schedule the production order with operations and job scheduling. 

https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/tasks/schedule-production-order-operations-job-scheduling

Here's additional information to learn more on operations scheduling: https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/operations-scheduling

Here's additional information to learn more on job scheduling:
https://learn.microsoft.com/en-us/dynamics365/supply-chain/production-control/job-scheduling

Hope this helps!
