### ISSUE TITLE
module 3 (case study master planning) - exercise 1 - clearer instructions needed

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#59]
# Module: 03, case study 2
#### Step: 14

Description of issue
the order was sent to credit management - please make sure users know to navigate to credit management, go to the credit management hold list and release the order -- then do the confirm sales order process again.

![image](https://user-images.githubusercontent.com/89986870/190902271-65f3f848-49ec-470d-a6b1-365bc65db520.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 3 / Case study 2 / Exercise 1 Step 15. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
Unable to replicate issue:

![image](https://user-images.githubusercontent.com/104943975/197307326-b94d0c82-2dd7-43e4-b5d7-2eae63e0f959.png)
