### ISSUE TITLE
Module 3 (case study Master Planning), exercise 2 - ISSUE, UNABLE TO COMPLETE

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#60]
# Module: 3
#### Step: 03 

Description of issue
* Step 3: "apples" does not exist in the wizard - so i took audio.. (see first screen shot)
* but even on step 9 after selecting item allocation keys, there are no unassigned item allocation keys showing on the screen (see second screen shot)
* On the next exercise step 3 does not show intercompany planning group 60 - when i select the one that was created in the previous exercise I get the error message showing the third screen shot below..

*** Please advise on how to fix**

![image](https://user-images.githubusercontent.com/89986870/190903046-87cb6b62-5cf7-4390-bfba-20e6d349f5b5.png)

![image](https://user-images.githubusercontent.com/89986870/190903320-b10b9ead-5ff4-4aa5-8f64-653c1c47a6e6.png)

![image](https://user-images.githubusercontent.com/89986870/190903427-811ce6d3-4e48-4cd4-91f5-2363af4d7673.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 3 / Case study 2 / Exercise 2 Step 3. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
This has been updated to reflect the appropriate value in the system and Audio has replaced apples in the content.
