### ISSUE TITLE
Module 5, exercise 1 - missing required info at various steps - ISSUE, UNABLE TO COMPLETE

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#61]
# Module: 5 (lab subcontracting for product manufacturing
#### Step: 15

Description of issue:
* In step 15 - there is no item called S0002 -- please advise how to proceed -- which details need to be filled in when creating this record?
* for now i took A0002 - but that is not correct because it got me into trouble in step 54 during the task to create activity based subcontracting (step 54)

#### Step: 45

Description of issue:
* In step 45 - there is no service unit called "hr" -- please advise how to proceed.
* for now i took ea and job, rather than hr and activity time - it was strange because when i clicked on details for the service terms i could change it to hours and activity - see pages below.

![image](https://user-images.githubusercontent.com/89986870/190912089-25309e78-f686-46b2-b0df-666afd2e8a9c.png)

![image](https://user-images.githubusercontent.com/89986870/190912070-c5215e5f-6403-4e0a-ac31-9406079f63c5.png)

#### Step: 54

Description of issue:
* In step 54 i am unable to select S0002 because that record did not exist in the beginning of this exercise.

Step 70 - because of the issue above, i was not able to activate version 2... see error message here:

![image](https://user-images.githubusercontent.com/89986870/190912302-8bd22502-f6b4-4fc4-8237-1109cb26aee6.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 5: Case study 3 / Exercise # 1 Step 15. We are reviewing this and will provide an update once a resolution is in place.

**Comment by chaast** [comment]
thank you for your support

**Comment by mstall1ngs** [comment]
Tested and successful with labs with exception of value S0002 exclusion. This has been updated and reflected on PR https://github.com/MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing/pull/47/files
