### ISSUE TITLE
Case Study 1a - exercise 4 - step 21 highlights there is a missing step in between step 14 and 15.

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#62]
# Case Study: 1a
#### Step: 21

Description of issue
Upon saving the record - i get an error to say that "the route group needs to be filled in for the line that mentions padding -- you need to fill in "Proc" as the route group to avoid the error message...

I have found the fix, but would you please update the labs to highlight this step to students?

Repro steps:
![image](https://user-images.githubusercontent.com/89986870/201762312-fff32335-8d5d-4cc1-8a12-c144b89ef95c.png)
![image](https://user-images.githubusercontent.com/89986870/201762906-1afc47ee-7c6d-4034-880e-96425d5b86e1.png)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! The route is created prior to creating the route relation as there has to be route details and assignments for the operation. The route contains the order of operations which sit within the route. The route group is automatically added to the grid after the first record is created for the Assembly operation and does not rectify the issue.

![image](https://user-images.githubusercontent.com/104943975/208784715-1b1ef535-5560-4522-adfd-96eec0c0e87f.png)

The steps for creating the route relation are in the next following steps: Step 23 through Step 35. A note has been made to ensure clarity on this action.
