### ISSUE TITLE
Lab 1b, exercise 10 - company USP2 records do not exist - exercise 9 is prerequisite

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#63]
# Lab 1b
## Exercise 10

i noticed that Exercise 9 is a prerequisite for exercise 10 -- please let the students know on the instructions, or please mark 9 as no longer a bonus exercise... thank you.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercises 10. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
Thank you for this suggestion. We've made changes for this to be clearer and excluded as a bonus exercise. 
![image](https://user-images.githubusercontent.com/104943975/233517515-c919e123-8aa3-4b6e-9041-0218b59e2ea3.png)
