### ISSUE TITLE
Case Study 3 Subcontracting - create a work cell -- error on resource groups

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#64]
# Case Study 3
### Task: create a work cell for subcontracting

Description of issue -- i have created a resource group, however at the ned, when i click save (step 29), i get a red error message to say "project resource data has not been populated. please populate the data by running the "populate project resources across all companies" batch job.

Where can i find this batch job please?

PS to be more specific - the issue occurred first time when I tried to select "Production" as the calendar. I tried the other calendar's too, but the error message remains. I can go ahead and save the record, but the calendar field is then empty.

Please note: Because of this, I am also unable to Activate the new version created under the section "create activity based subcontracting rule, step 69".

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 5 / Case study 3 / Exercises 1. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
The error message may have appeared if the project resources were not allocated when adding the production calendar under the Calendar FastTab to the eBookSub resource groups. 

Here's guidance on the root cause of the error and resolutions:

- Review the applicable resources. The project resources are not setup, please follow the steps below to create:
     - Go to **Project management and accounting **>** Project resources **>** Resources list**.
     - Click **New resource**.
     - In the **Worker** field, enter or select a value.
     - In the **Calendar** field, enter or select a value.
     - In the **Period code** field, enter or select a value.
     - Click **Create**.
     - Click **Cost prices**.
     - Click **Cost price - hour**.
     - Click **New**.
     - In the **Effective date** field, enter a date.
     - In the **Cost price** field, enter a number.
     - Click **Save**.
     - Close the page.
     - Click **Sales prices**.
     - Click **Sales price - hour**.
     - Click **New**.
     - In the **Effective date** field, enter a date.
     - In the **Pricing** field, enter a number.
     - In the **Valid for** field, select an option.
     - Click **Save**.
     - Close the page.
- The calendar is used to schedule the project and the working time of the resources that are reserved for the project. The error can occur if no calendar is associated with the resource or resource group, or if the associated calendar isn't correctly set up (for example, it has no working times, or its efficiency as a percentage is 0 [zero]).
    -  You must set up a calendar and associate it with an employee or a worker. 
    - Verify that a calendar is associated with the resource or resource group
    - The calendar is using a **24hr Production**. Ensure that working times are composed.
    - Follow the steps above but when on the **Applicable Resources** page, select **View resource**
    - On the **Resources** page or the **Resource groups** page, on the **Calendars** FastTab, make sure that a calendar is associated with the resource or resource group
    - Review the setup of the calendar
- Populate project resources across all companies batch job
    - The data in this batch job is needed to calculate resource capacity through the associated calendar.
    - You can do this by enabling the resource scheduling performance enhancement
    - To improve resource scheduling performance, a feature is available that allows users to reduce the time that it takes to launch the resource availability form. This removes the resource capacity roll-up synchronization process and uses the **ResProjectResource** table to speed up the resource lookup vs the **ResRollup** table, which would no longer be used.
    -  To enable resource scheduling performance enhancement, complete the following steps.
    - Go to **Feature management **>** All**, and in the feature list, locate **Enable project resource scheduling performance enhancement** feature.
    - Select **Enable now**.
    - Refresh your browser, and then go to **Project management and accounting **>** Periodic **>** Project resources **>** Synchronize resource calendars capacity across all companies**.
    - Set **Remove existing capacity records** to **Yes** to remove previous data. If you want to generate incremental data, set it to **No**.
    - In the **Period code** field, select the period in which data should be generated. If you select a period code, a start and end date do not need to be defined. 
    - If you leave the Period code field blank, select specific start and end dates to generate data.
    - Select OK.
This will distribute general data to the **ResCalendarCapacity** table across all companies in your environment, so the batch job only needs to be run in one legal entity. The data in this batch job is needed to calculate resource capacity through the associated calendar.
    - Go to **Project management and accounting **>** Periodic **>** Project resources **>** Populate project resources across all companies** and then select **OK**. This is the data upgrade script for general data in the **ResProjectResource**,** ResCalendarDateTimeRange**, and** ResEffectiveDateTimeRange** tables. If this is not run, you will receive a warning when you try to execute resource scheduling operations.
